set search_path = wpf_training8_central;
 
( 
 SELECT DISTINCT BC.METRIC_ID AS BC_ID,
   BC.METRIC_NAME AS BC_NAME,
   TC_RULES.TC_ID AS TC_ID,
   TC_RULES.TC_NAME AS TC_NAME,
   TC_BC.AGGREGATE_WEIGHT AS TC_WT,
   TC_BC.METRIC_CRITICAL AS TC_CRITICAL,
   TC_RULES.QR_ID AS QR_ID,
   TC_RULES.QR_NAME AS QR_NAME,
   TC_RULES.QR_GROUP AS QR_GROUP,
   TC_RULES.QR_CRITICAL AS QR_CRITICAL,
   TC_RULES.QR_WT AS QR_WT,
   TC_RULES.SD_ID AS SD_ID,
   TC_RULES.SD_NAME AS SD_NAME,
   TC_RULES.TH1 AS TH1,
   TC_RULES.TH2 AS TH2,
   TC_RULES.TH3 AS TH3,
   TC_RULES.TH4 AS TH4,
   REPLACE(TC_RULES.LANGUAGE, 'ALL', '.ALL')  AS LANGUAGE
 FROM   (SELECT DISTINCT TC.METRIC_ID AS TC_ID,
     TC.METRIC_NAME AS TC_NAME,
     RULES.QR_ID AS QR_ID,
     RULES.QR_NAME AS QR_NAME,
     RULES.M_GRP AS QR_GROUP,
     QR_TC.AGGREGATE_WEIGHT AS QR_WT,
     QR_TC.METRIC_CRITICAL AS QR_CRITICAL,
     RULES.SD_ID,
     RULES.SD_NAME,
     RULES.TH1 AS TH1,
     RULES.TH2 AS TH2,
     RULES.TH3 AS TH3,
     RULES.TH4 AS TH4,
     OT.OBJECT_TYPE_NAME AS LANGUAGE
   FROM  (
--Quality Distribution
SELECT  QR.METRIC_ID AS QR_ID,
       QR.METRIC_NAME AS QR_NAME,
       QR.METRIC_GROUP as M_GRP,
       SD.METRIC_ID AS SD_ID, 
       SD.METRIC_NAME AS SD_NAME,
       THRESHOLD.THRESHOLD_1 AS TH1,
       THRESHOLD.THRESHOLD_2 AS TH2,
       THRESHOLD.THRESHOLD_3 AS TH3,
       THRESHOLD.THRESHOLD_4 AS TH4
     FROM  DSS_METRIC_STATUS_THRESHOLDS THRESHOLD,
       DSS_METRIC_TYPE_TREES QR_SD,
       DSS_METRIC_TYPES QR,
       DSS_METRIC_TYPES SD
     WHERE THRESHOLD.METRIC_ID = QR_SD.METRIC_PARENT_ID
     AND THRESHOLD.STATUS = QR_SD.METRIC_INDEX
     AND THRESHOLD.METRIC_ID = QR.METRIC_ID
     AND QR_SD.METRIC_ID = SD.METRIC_ID
    
     UNION
    --Quality Rule/Measure
     SELECT  QR.METRIC_ID AS QR_ID,
       QR.METRIC_NAME AS QR_NAME,
       QR.METRIC_GROUP AS M_GRP,
       -1 AS SD_ID, 
       NULL AS SD_NAME,
       THRESHOLD.THRESHOLD_1 AS TH1,
       THRESHOLD.THRESHOLD_2 AS TH2,
       THRESHOLD.THRESHOLD_3 AS TH3,
       THRESHOLD.THRESHOLD_4 AS TH4
     FROM  DSS_METRIC_TYPES QR,
       DSS_METRIC_STATUS_THRESHOLDS THRESHOLD
     WHERE QR.METRIC_ID = THRESHOLD.METRIC_ID
     AND NOT EXISTS (SELECT QR_SD.METRIC_PARENT_ID
         FROM DSS_METRIC_TYPE_TREES QR_SD
         WHERE QR_SD.METRIC_PARENT_ID = THRESHOLD.METRIC_ID
         AND QR_SD.METRIC_INDEX = THRESHOLD.STATUS)
     UNION
--Hard Coded Quality Rules/Measure
     SELECT  QR.METRIC_ID AS QR_ID,
       QR.METRIC_NAME AS QR_NAME,
       QR.METRIC_GROUP AS M_GRP,
       -1 AS SD_ID, 
       NULL AS SD_NAME,
       10 AS TH1,
       65 AS TH2,
       85 AS TH3,
       160 AS TH4
     FROM  DSS_METRIC_TYPES QR        
     WHERE QR.METRIC_ID NOT IN (SELECT METRIC_ID FROM DSS_METRIC_STATUS_THRESHOLDS)
         ) RULES  LEFT OUTER JOIN
         DSS_METRIC_TYPE_TREES QR_TC ON (QR_TC.METRIC_ID = RULES.QR_ID
                 AND RULES.M_GRP  in (1, 5, 15)) 
     LEFT OUTER JOIN DSS_METRIC_TYPES TC ON (QR_TC.METRIC_PARENT_ID = TC.METRIC_ID)
     LEFT OUTER JOIN DSS_METRIC_PARAM_TYPES MT ON (MT.METRIC_ID = RULES.QR_ID)
     LEFT OUTER JOIN DSS_OBJECT_TYPES OT ON (OT.OBJECT_TYPE_ID = MT.OBJECT_TYPE_ID)
  ) TC_RULES,
  DSS_METRIC_TYPE_TREES  TC_BC,
  DSS_METRIC_TYPES BC
WHERE  TC_BC.METRIC_ID = TC_RULES.TC_ID 
AND TC_BC.METRIC_PARENT_ID = BC.METRIC_ID  
)
